GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU2NzM4OTEzLCJleHAiOjE3NTY3Mzg5MzN9.17XSdoUVwLEzweBuYY7_17aUtIUpVoM3263_dIMKQyk

### Register User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Ezra",
    "email": "ezra@example.com",
    "password": "12345678",
    "confPassword": "12345678"
}

### Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ezra@example.com",
    "password": "12345678"
}


###
GET http://localhost:5000/token

###

DELETE http://localhost:5000/logout


### Register Alat
POST http://localhost:5000/alat
Content-Type: application/json

{
    
}