# 1. Ubah ini menjadi 'false' untuk menolak koneksi anonim
allow_anonymous false

# 2. Tambahkan baris ini untuk menunjuk ke file password
#    Gunakan path lengkap Windows
password_file C:\Agrifam\react-irrigation\backend\mosquitto\passwd

# Baris listener Anda sudah benar
listener 1883 0.0.0.0